export const GET_THREAD_REQUEST = 'GET_THREAD_REQUEST'
export type GET_THREAD_REQUEST = typeof GET_THREAD_REQUEST

export const GET_THREAD_FAILURE = 'GET_THREAD_FAILURE'
export type GET_THREAD_FAILURE = typeof GET_THREAD_FAILURE

export const GET_THREAD_SUCCESS = 'GET_THREAD_SUCCESS'
export type GET_THREAD_SUCCESS = typeof GET_THREAD_SUCCESS

export const GET_THREADS_REQUEST = 'GET_THREADS_REQUEST'
export type GET_THREADS_REQUEST = typeof GET_THREADS_REQUEST

export const GET_THREADS_FAILURE = 'GET_THREADS_FAILURE'
export type GET_THREADS_FAILURE = typeof GET_THREADS_FAILURE

export const GET_THREADS_SUCCESS = 'GET_THREADS_SUCCESS'
export type GET_THREADS_SUCCESS = typeof GET_THREADS_SUCCESS

export const CREATE_THREAD_REQUEST = 'CREATE_THREAD_REQUEST'
export type CREATE_THREAD_REQUEST = typeof CREATE_THREAD_REQUEST

export const CREATE_THREAD_FAILURE = 'CREATE_THREAD_FAILURE'
export type CREATE_THREAD_FAILURE = typeof CREATE_THREAD_FAILURE

export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS'
export type CREATE_THREAD_SUCCESS = typeof CREATE_THREAD_SUCCESS

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST'
export type GET_MESSAGES_REQUEST = typeof GET_MESSAGES_REQUEST

export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE'
export type GET_MESSAGES_FAILURE = typeof GET_MESSAGES_FAILURE

export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export type GET_MESSAGES_SUCCESS = typeof GET_MESSAGES_SUCCESS

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export type SEND_MESSAGE_REQUEST = typeof SEND_MESSAGE_REQUEST

export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
export type SEND_MESSAGE_FAILURE = typeof SEND_MESSAGE_FAILURE

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export type SEND_MESSAGE_SUCCESS = typeof SEND_MESSAGE_SUCCESS

export const UN_NEW_THREAD_MESSAGES_REQUEST = 'UN_NEW_THREAD_MESSAGES_REQUEST'
export type UN_NEW_THREAD_MESSAGES_REQUEST = typeof UN_NEW_THREAD_MESSAGES_REQUEST

export const UN_NEW_THREAD_MESSAGES_FAILURE = 'UN_NEW_THREAD_MESSAGES_FAILURE'
export type UN_NEW_THREAD_MESSAGES_FAILURE = typeof UN_NEW_THREAD_MESSAGES_FAILURE

export const UN_NEW_THREAD_MESSAGES_SUCCESS = 'UN_NEW_THREAD_MESSAGES_SUCCESS'
export type UN_NEW_THREAD_MESSAGES_SUCCESS = typeof UN_NEW_THREAD_MESSAGES_SUCCESS

export const OPEN_THREAD = 'OPEN_THREAD'
export type OPEN_THREAD = typeof OPEN_THREAD

export const CLOSE_THREAD = 'CLOSE_THREAD'
export type CLOSE_THREAD = typeof CLOSE_THREAD

export const SEND_MESSAGE = 'SEND_MESSAGE'
export type SEND_MESSAGE = typeof SEND_MESSAGE
