export const GET_USER_BY_TOKEN_REQUEST = 'GET_USER_BY_TOKEN_REQUEST'
export type GET_USER_BY_TOKEN_REQUEST = typeof GET_USER_BY_TOKEN_REQUEST

export const GET_USER_BY_TOKEN_SUCCESS = 'GET_USER_BY_TOKEN_SUCCESS'
export type GET_USER_BY_TOKEN_SUCCESS = typeof GET_USER_BY_TOKEN_SUCCESS

export const GET_USER_BY_TOKEN_FAILURE = 'GET_USER_BY_TOKEN_FAILURE'
export type GET_USER_BY_TOKEN_FAILURE = typeof GET_USER_BY_TOKEN_FAILURE

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export type SIGN_IN_REQUEST = typeof SIGN_IN_REQUEST

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export type SIGN_IN_SUCCESS = typeof SIGN_IN_SUCCESS

export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export type SIGN_IN_FAILURE = typeof SIGN_IN_FAILURE

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export type SIGN_UP_REQUEST = typeof SIGN_UP_REQUEST

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export type SIGN_UP_SUCCESS = typeof SIGN_UP_SUCCESS

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export type SIGN_UP_FAILURE = typeof SIGN_UP_FAILURE

export const SIGN_OUT = 'SIGN_OUT'
export type SIGN_OUT = typeof SIGN_OUT
