export const GET_AVATAR_REQUEST = 'GET_AVATAR_REQUEST'
export type GET_AVATAR_REQUEST = typeof GET_AVATAR_REQUEST

export const GET_AVATAR_FAILURE = 'GET_AVATAR_FAILURE'
export type GET_AVATAR_FAILURE = typeof GET_AVATAR_FAILURE

export const GET_AVATAR_SUCCESS = 'GET_AVATAR_SUCCESS'
export type GET_AVATAR_SUCCESS = typeof GET_AVATAR_SUCCESS

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST'
export type UPDATE_AVATAR_REQUEST = typeof UPDATE_AVATAR_REQUEST

export const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE'
export type UPDATE_AVATAR_FAILURE = typeof UPDATE_AVATAR_FAILURE

export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS'
export type UPDATE_AVATAR_SUCCESS = typeof UPDATE_AVATAR_SUCCESS
